### PR TITLE
Fix PiPL writer on macOS, format code and add a few more wrappers

### PR DESCRIPTION
**Pull request by AdrianEddy**
- PiPL on macOS uses a different byte order, so we need to handle macOS differently
- Format code using `cargo fmt`
- Added a few more wrappers in pf.rs
- `Justfile` for `portable` example builds the full bundle on macOS

### CODE REVIEW

**Comment by virtualritz** [comment]
That looks nice!

I saw you used `cstr-literal`. Are you aware of [`ustr`](https://crates.io/crates/ustr)?

**Comment by AdrianEddy** [comment]
> I saw you used `cstr-literal`. Are you aware of [`ustr`](https://crates.io/crates/ustr)?

Never heard of `ustr`, will check it out. I still have plenty of work here, hopefully will add more updates soon. Currently working on getting the bindings/examples to be proper Rust rather than C-in-Rust

**Comment by AdrianEddy** [comment]
Good news is that doing `just build` gives you a working plugin ready to use both on Windows and macOS now

**Comment by virtualritz** [comment]
> Good news is that doing `just build` gives you a working plugin ready to use both on Windows and macOS now

That absolutely rocks.

I should try to find some time between the years to dig out some of the plug-ins I wrote and turn at least one into an example.

**Pull request merged**
