### PR TITLE
High level API

### LINKED ISSUE #36: High level interface
I'm designing a high level plugin interface for the bindings, and my general idea is to have something like:

```rust
struct PortablePlugin { }
impl AdobePlugin for PortablePlugin {
    fn can_load(_host_name: &str, _host_version: &str) -> bool { true }
    fn new() -> Self { Self {} }

    fn handle_command(&mut self, cmd: Command) {
        match cmd {
            Command::About { mut out_data, .. } => {
                out_data.set_return_msg("Test plugin."));
            }
            Command::Render { in_data, mut params, output, .. } => {
                // ...
            }
            Command::GpuDeviceSetup { in_data, mut out_data, extra/*: GPUDeviceSetupExtra*/ } => { ... }
            // ...
        }
    }
}

register_plugin!(PortablePlugin);
```

basically the idea is to only expose relevant and valid data in each command, including all `extra`s properly casted. I have that implemented so far, but I have a few concerns I wanted to discuss:

## Struct instances
1. Should we create and maintain global instance for user? What I imagine is that `PortablePlugin` struct would be stored in `global_data` and would be a single object alive for the entire time the project is open (and any plugin instance is added to the layer)
2. Should we create and maintain sequence instance for user? That would be a separate struct, which is unique per every layer where the plugin is applied. This would be stored in `sequence_data` and I imagine I would require the user to make this struct `serde::Serialize` and `serde::Deserialize` and automatically handle flattening the data with `bincode`. Also that struct should be Send + Sync I believe, because AE can call the commands from any thread at any time? Is that correct?

I believe these two points are very useful for almost all plugins and at the same time quite time-consuming to implement properly by the user.
Pros:
- User can focus on just his actual plugin code without worrying about complicated details of Handles and flattening
- Much easier to get started with writing plugins

Cons:
- A bit of memory overhead, since the instances would be always created. But since we're talking about video processing plugins here, any overhead like that is nothing compared to actual pixels processing so it should be fine. We could maybe make this optional with a `register_plugin` macro parameter or something

## Parameters
1. What do you think to create something like `ParameterRegistry`, which would be a manager for user params, with the enum-based getter/setter provided by user, and all parameters would be defined and retrieved using this enum. Something like:
```rust
enum MyParams {
    MixChannels
};
fn handle_command(&mut self, cmd: Command) {
    match cmd {
        Command::ParamsSetup { mut params } => {
            params.add_param(MyParams::MixChannels, 
                "Mix channels", 
                ae::FloatSliderDef::new()
                    .set_value(10.0)
                    .precision(1)
                    .display_flags(ae::ValueDisplayFlag::PERCENT)
            );
        }
        Command::Render { mut params, .. } => {
            let slider = params.get::<ae::Param::FloatSlider>(MyParams::MixChannels);
            // slider.value()
        }
    }
}
register_plugin!(PortablePlugin, MyParams);
```
That struct would maintain params array, indexes and counts (and would be stored in global instance data), so users won't have to worry about it. 

I'll have more things to discuss once I get further, but let's start with these.

Let me know your thoughts, thanks!

CC @virtualritz  @mobile-bungalow

### PR DESCRIPTION
**Pull request by AdrianEddy**
Initial rough idea for the high level API - definitely not it's final form and implementation yet, there's a lot to still implement here, but the basic examples do work already

I moved pf.rs into `pf/mod.rs` and separated out `parameters.rs` from it

There's a global `Justfile` that handles bundle creation, which needs to be included by the user. This would have to be downloaded by users separately from the repo (unless there's a way to know the path of the crate downloaded contents, but I don't think there is)

Closes #36

### CODE REVIEW

**Comment by AdrianEddy** [comment]
@virtualritz Please take a look around here: https://github.com/AdrianEddy/after-effects/tree/master/premiere/src and let me know what do you think about this structure, where every suite has it's own file. I'd want to do the same for the after effects suites, what do you think?

**Comment by virtualritz** [comment]
> [...] let me know what do you think about this structure, where every suite has it's own file.

Makes total sense. I had something like this planned but never got to it. :grin:

**Comment by AdrianEddy** [comment]
`ae::suites::World2` vs `ae::WorldSuite2` ?
The former is more rusty, but the latter is maybe easier to write and closer to the Adobe API? Thoughts?

**Comment by virtualritz** [comment]
I'd forget the "Adobe API". Make it as rusty as possible. Would you still have the suites anyway? Wouldn't that not just be `impl`s on `World`?

Afaik it's the [CoSa](https://www.after-effects.fr/cosa-after-effects/) API anyway, with lots of stuff added by Adobe over the years. :grin:

**Comment by AdrianEddy** [comment]
You're right, the `impl on World` way is the best way. 
We're lucky nobody warned me about the massive size of the Adobe SDK, and now I'm too deep into this to leave haha :D

So, I **fully** wrapped a few AEGP suites, including documentation which I had to source from both the header files and the adobe docs, while converting it to proper rustdoc with links to items etc. 

By that time, I had seen enough of these suites interfaces to realize that simply `WorldSuite` to `World` wrapper is not possible, because many of these suites have functions that operate on different items, and many items (eg layer) are connected to multiple suites. This, and the amount of suites and functions in them, makes creating **proper** wrappers extremely time consuming. 

So the way I choose to go about this is to mindlessly wrap the suites in their entirety, and then (with a helper macro) optionally add a `World` type which calls the wrapped functions from the suite. I tried to structure it logically both in files and in the interface/docs. So we have `aegp::suites::World` and `aegp::World`, but they are both defined in `src/argp/suites/world.rs`. Please check out the files and let me know what do you think about this approach. I think it's maintainable. 
I currently only wrapped `World` and `Camera` like that, I'll proceed to wrap more.
One drawback is that the doc comments need to be repeated, but maybe that's a good thing as they can be slightly modified to better point to "self"

I'm currently focusing just on the AEGP suites, I'll proceed to other suites/items with the same pattern, unless you have any feedback or ideas.

https://github.dev/AdrianEddy/after-effects/blob/master/src/aegp/suites/world.rs
and check out all other files in the AEGP suites folder and aegp/mod.rs

The generated docs look quite nice too.

I also made a list of the available vs wrapped suites in the entire SDK in the main README

**Comment by virtualritz** [comment]
Yeah, that's why I only wrapped the suites I needed for the plugin I was working on. All of it is just a lot.
And some suites are niche uses.

One way to look at it is to also just wrap the most used suites and leave the rest to users of this crate that need them to open PRs for.

> https://github.dev/AdrianEddy/after-effects/blob/master/src/aegp/suites/world.rs

My first feedback is regarding naming. I wasn't aware of [this](https://rust-lang.github.io/api-guidelines/naming.html) when I started working on this (I was a Rust n00b) so many names could be oxidized.

I.e `PluginID` should be [`PluginId`](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case) etc. and all getters need the [`get_` removed](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter).

**Comment by AdrianEddy** [comment]
about the `get_` naming - yeah, but take a look at `World`, it has `size()` which calls `get_size` from the suite. Suite itself is not an object, so `get_` prefix is appropriate there, because there's no self, and there are a lot of different methods, operating on different items. 

`get_` is be removed from items' methods, but I think it should stay in suites

**Comment by virtualritz** [comment]
I saw this, my counter points would be that:

1. `WorldHandle` is essentially the object, not `self`. These are getters in the sense of the doc I linked.

2 . For someone using this crate, when resorting to using a suite over the `World` `impl` for any reason, they should see the same function names (developer exprerience -- DX).
 
Otherwise `World` looks *very* nice.

I always find the `r#type` ugly. Bindgen generates `type_`. Also ugly but less so? Some people use `typ` or another word (`kind`). That's a detail.

I would have getter names reflect structs they return 1:1 though. I.e. `World::pf_effect_world()` should be `World::effect_world()` since it returns an `EffectWorld`. 

I guess I'm saying: be ruthless when oxidizing names. :grin:

**Comment by AdrianEddy** [comment]
`r#type` is indeed ugly, I'll go with `world_type` then, it's not as nice as `type()`, but I think it's better than `.type_()`. 
`kind()` would be nice, but then `kind()` returning `WorldType` is not intuitive. We have to keep in mind that the API will also be comsumed with people already familiar with the C++ SDK, so we shouldn't change the API too much. 

Ok I'll remove `get_`s from suite functions and proceed to oxidize the rest of the SDK.

I'm not planning to wrap more suites that we already have, there's just too many of them. Like you said, we'll leave that to other users to provide PRs if they need them, but nonetheless I want to make a solid foundation with the suites we have.

**Comment by AdrianEddy** [comment]
What's the `assume!` macro for? Can i remove it?

I wrapped the drawbot suite + item approach and it turned out quite nice

**Comment by virtualritz** [comment]
> What's the assume! macro for? Can i remove it?

Feel free to remove anything you deem superfluous. We can always bring it back if we need it again. :grin:

**Comment by AdrianEddy** [comment]
We're getting more rusty, yay!

I wrapped the `Item`, `Layer` and `Footage` and with the latest changes, I turned this:
```rust
if let Ok(interface_suite) = ae::aegp::suites::PFInterface::new() {
    if let Ok(layer_suite) = ae::aegp::suites::Layer::new() {
        if let Ok(footage_suite) = ae::aegp::suites::Footage::new() {
            let layer = interface_suite.effect_layer(in_data.effect_ref())?;
            let item = layer_suite.layer_source_item(layer)?;
            let footage = footage_suite.main_footage_from_item(item)?;
            let footage_path = footage_suite.footage_path(footage, 0, 0);
            
        }
    }
}
```

into this
```rust
let footage_path = in_data.effect()
                          .layer()?
                          .source_item()?
                          .main_footage()?
                          .path(0, 0)?;
```

Here's an example of wrapped `Item`, which uses functions from multiple suites: https://github.com/AdrianEddy/after-effects/blob/master/src/aegp/suites/item.rs#L268-L386

Suites in these item wrappers are acquired lazily, so if you don't call a function which uses a given suite, it won't be acquired. This is also important when some suites are not available (eg. in Premiere) - in this case the function call returns an `Err`, instead of returning an error in the Item's constructor.

I assume acquiring and releasing suites is very cheap (like just adding a reference), but I don't know that for sure. Do you happen to know if acquiring and releases suites does anything heavy?

All functions in suites are also now able to accept either `ae_sys::AEGP_ItemH`, `ItemHandle` or `Item`, and I believe that's a zero-cost abstraction

**Comment by AdrianEddy** [comment]
I'm getting closer to finishing this thing, and today `Parameters` got a new life.

I basically written everything from scratch. I'm sorry to throw away most of your params code, but hear me out:
The current implementation had a few major issues:
1. Memory of labels was leaked in `into_raw()`
2. It was not possible to mutate the parameters after calling `to_param()`, because it created a copy, while it should be a reference to union's data
3. `param_def_boxed: std::mem::ManuallyDrop<Box<ae_sys::PF_ParamDef>>,` is extremely unclear, with zero help from the rust compiler
4. A mix of macros and raw implementations

So, let's start with the basics: memory!
It may look like the `ParamDef` memory management is confusing, but it's actually pretty simple, and it can be clearly and safely represented by [this enum](https://github.com/AdrianEddy/after-effects/blob/4311f2704ae2bda38b350189156688e129bcbb6e/src/lib.rs#L567-L600):
```rust
pub enum Ownership<'a, T: Clone> {
    AfterEffects(&'a T),
    AfterEffectsMut(&'a mut T),
    Rust(T),
}
```
The only case where we don't own `ParamDef` memory is the `params` parameter in EffectMain. Lifetime of that `params` is also clear, it can only live as long as the EffectMain call. With this, we can immediately convert that `*mut *mut PF_ParamDef` to a `&[*mut PF_ParamDef]` slice in EffectMain and let it live until the end of EffectMain. From that, every other function that touches parameters derives both the reference and lifetime, so if you want to get or set a slider value, you have to reference that original `params` value. This is done [here](https://github.com/AdrianEddy/after-effects/blob/4311f2704ae2bda38b350189156688e129bcbb6e/src/pf/parameters.rs#L835-L857), where eg. `FloatSliderDef` takes a reference and enforces that it is not stored any longer than the parent `ParamDef`.

In every other case, we create the `ParamDef` memory and we have the ownership (`Ownership::Rust`). If we call `checkout`, then AE simply fills out the provided memory, and we have to call `checkin`, but that memory is still Rust's.

What about the label's memory? The string pointer just has to outlive the call to `add_param`, and since we now have the correct lifetimes and references in all structs, that's not an issue, and is done eg. [here](https://github.com/AdrianEddy/after-effects/blob/4311f2704ae2bda38b350189156688e129bcbb6e/src/pf/parameters.rs#L1046-L1047)

When parameters are checked out, we create an owned `Ownership::Rust` value, which has to live for as long as you'll want to use the parameters data, before it's checked in on drop.
A nice bonus of correct references and lifetimes, is that every call to `set_...` sets `change_flags = CHANGED_VALUE` for you

Example:
```rust
let mut param = params.get_mut(Params::Color, None, None, None)?; // Param gets checked out here
let mut color = param.as_color_mut()?;

let current_color = color.value();
color.set_value(ae::Pixel8 { ... }); // and `param`'s CHANGED_VALUE flag is set inside this call

// param is checked in on drop
```

Another problem was that specific `ParamDef`s were kind of builders, but not really. Since the memory is referenced now, making it a builder at the same time was tricky, but I settled with this design:
```rust
params.add_param(Params::MixChannels, "Mix channels", ae::FloatSliderDef::setup(|f| {
    f.set_valid_min(0.0);
    f.set_slider_min(0.0);
    f.set_valid_max(200.0);
    f.set_slider_max(200.0);
    f.set_value(10.0);
    f.set_default(10.0);
    f.set_precision(1);
    f.set_display_flags(ae::ValueDisplayFlag::PERCENT);
}));
```
I think it's not bad.

On top of all parameter handling, we have `Parameters` struct. which is basically a param manager, which maps params defined by a rust `enum` to int indices for Ae, [sets DISK_ID](https://github.com/AdrianEddy/after-effects/blob/4311f2704ae2bda38b350189156688e129bcbb6e/src/pf/parameters.rs#L1014-L1021) automatically so it's safe to change order or add params in different versions of your plugin, and simplifies adding, getting and checking out params. 
Mapping HashMap is created in `Command::ParamsSetup` and reference to it is passed to every other command call

simply calling `params.get(MyParams::My, None, None, None)` gets you ParamDef, either referenced from EffectMain's `params` ptr or checked out using `param_checkout`. If you pass time, it will be checked out at a different time.

[Adding groups](https://github.com/AdrianEddy/after-effects/blob/4311f2704ae2bda38b350189156688e129bcbb6e/src/pf/parameters.rs#L1022-L1042) (twirly things) is also supported

I'm pretty happy with this design, but as always I'm open to feedback. Check out [parameters.rs](https://github.com/AdrianEddy/after-effects/blob/4311f2704ae2bda38b350189156688e129bcbb6e/src/pf/parameters.rs), [define_param_wrapper!](https://github.com/AdrianEddy/after-effects/blob/4311f2704ae2bda38b350189156688e129bcbb6e/src/macros.rs#L252-L253) macro and [Ownership](https://github.com/AdrianEddy/after-effects/blob/4311f2704ae2bda38b350189156688e129bcbb6e/src/lib.rs#L567-L600) enum

**Comment by virtualritz** [comment]
Hey @AdrianEddy, isn't this in a state where it would warrant a merge and release? Even if it's not perfect (docs etc.)?

**Comment by AdrianEddy** [comment]
sorry about the delay, yes it's almost ready, but I had to take care of other things since then. I definitely want to get this finished soon, so if you don't necessarily need it merged right now, I'd wait a few more weeks until I have my plugin fully finished in case this needs any changes.

**Comment by valadaptive** [comment]
I'm playing around with this API a bit and I see that the `Parameters` API uses 32-bit MurmurHash to determine parameter IDs.

While the probability of a collision between IDs should still be quite low, it might be better to use a counter to generate IDs or include some sort of collision checking. With 64- or 128-bit IDs, I wouldn't be as concerned, but 32 bits seems a bit low.

**Comment by AdrianEddy** [comment]
> I'm playing around with this API a bit and I see that the `Parameters` API uses 32-bit MurmurHash to determine parameter IDs.
> 
> While the probability of a collision between IDs should still be quite low, it might be better to use a counter to generate IDs or include some sort of collision checking. With 64- or 128-bit IDs, I wouldn't be as concerned, but 32 bits seems a bit low.

We can't use 64-bit because the id field in AE is only 32-bit. We also can't use a counter, because the idea behind this is to set the "disk id" which is saved in the project file, and it should continue to work even if you update the plugin and change parameters. The goal is that unique parameter name = unique disk id, so even if you add or change parameters later, the order doesn't matter.

I agree that there exists small chance of a collision, but I couldn't think of a better solution than this. Other than passing the responsibility for this entirely to the user of this API (which you can do by using `set_id` in `add_customized`)

**Comment by valadaptive** [comment]
@AdrianEddy Would you mind enabling the Issues tab on your fork?

**Comment by AdrianEddy** [comment]
Sorry it took this long but it is now finally ready to merge. I'm not sure if you want to review it though as it's massive 🙂

I've written the documentation for most important parts, but there are still a lot of structs left undocumented. I would have to copy and rewrite the entire Adobe docs which is too much for me. I believe what's documented + examples are enough

I changed the version to 0.2.0, and after merging it's ready to publish to crates.io

**Comment by virtualritz** [comment]
Thank you so much for this and yeah, no time to review for now.
Everything I saw looked awesome and well though-out.
 
I'm working full time on an in-house node-based 2D/3D compositing system backed by OpenImageIO and 3Delight. In Rust. That part is closed source, unfortunately, but the OIIO bindings are OSS.

Writing an AfterEffects plug-in for fun and no profit or porting my AtomKraft/Ae Rust re-write to this, both activities that would be a nice way to "review" this, are wishful thinking atm. :grin:

**Comment by virtualritz** [comment]
Everything is published on `crates.io`.
I could not even test any builds as I'm on a Linux box. So kringers fossed.

TODO: make the `docs.rs` build succeed. I will open an issue for that.

**Pull request merged**
